### ISSUE TITLE
[만화 뷰어] 만화 뷰어 페이지

### ISSUE THREAD

**Issue by akswnd98** [GiveUsMoney/FanFixiv-user-page#35]
> https://github.com/GiveUsMoney/FanFixiv/issues/55 참고

**Task 설명**
만화 뷰어 페이지를 제작합니다.

**TODO**

- [ ]  시리즈 목록 표시
    - [ ]  시리즈가 아닐 경우 표시하지 않음
- [ ]  이미지 표시 (가로 사이즈에 맞게)
- [ ]  제목 표시
- [ ]  번역가 표시
    - ~~클릭시 #프로필 페이지로 이동~~ (개발 예정)
- [ ]  등록일 표시
- [ ]  원작자 표시
    - 클릭시 원작자 검색 상태로 #만화-목록으로 이동
- [ ]  번역후기 표시
- [ ]  출처 표시 (상단 또는 하단에 링크 표시)
    - [ ]  출처는 원작자, 번역가 둘다 표시하며 번역가 출처는 없을 경우 표시하지 않음.
- [ ]  ~~신고 기능~~ (개발 예정)
- [ ]  수정/삭제 기능 (업로드한 번역가만 수정/삭제 가능)

**레퍼런스**
- 네이버 웹툰: https://comic.naver.com/webtoon/detail?titleId=792651&no=33&weekday=sat
