### ISSUE TITLE
[만화 등록] 만화 등록 페이지

### ISSUE THREAD

**Issue by akswnd98** [GiveUsMoney/FanFixiv-user-page#44]
> https://github.com/GiveUsMoney/FanFixiv/issues/57

**Task 설명**
만화 등록 페이지를 작성합니다.

**TODO**
- [ ]  ~~번역가가 아니면 만화 등록 불가~~
- [ ]  만화 등록 전 약관 동의 (번역가 프로필 추가 시 삭제 요망)
- [ ]  원작, 번역 링크 등록 (번역요청으로 등록할 경우 자동으로 입력됨)
    - [ ]  원작 링크에 따라서 로고가 변경됨
    - [ ]  중복검사
        - 링크 중복 등록 가능
        - 단, 중복된 링크일 경우 주의를 주도록 함
    - [ ]  번역 링크의 경우 생략이 가능
- [ ]  파일 업로드 (프론트엔드분들과 컨텍 필요)
    - [ ]  파일 드래그 앤 드롭으로 이미지 업로드 기능
    - [ ]  업로드 아이콘 눌러서 이미지 업로드 기능
    - [ ]  #58
    - [ ]  업로드 이미지 제거, 순서이동 기능
- [ ]  썸네일 업로드 기능
    - [ ]  썸네일 미업로드시 첫번째 이미지 썸네일 리사이징, Crop 기능
- [ ]  태그 등록
    - [ ]  #입력으로 태그를 등록 (단. 원작자는 필수 입력)
    - [ ]  *원작자 태그의 경우 링크를 분석해 자동으로 원작자를 선택함*
- [ ]  번역 후기
- [ ]  콘텐츠 카드 미리보기
    - 클릭시 #58 으로 이동

**레퍼런스**
https://github.com/GiveUsMoney/FanFixiv/issues/57
